# """
# Django settings for stablelinkcapital project.

# Generated by 'django-admin startproject' using Django 5.2.8.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/
# """

# from pathlib import Path

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

# import os
# from dotenv import load_dotenv
# load_dotenv()

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = os.getenv(
#     "SECRET_KEY",
#     "django-insecure-2*i#bz-_d3kayf8_^&rl+6dha(^do1m6kwa$sx0xrg02=t4(@i"  # fallback for local
# )



# DEBUG = os.getenv("DEBUG", "True") == "True"
# DEBUG = True  # forces debug always


# ALLOWED_HOSTS = [
#     'localhost',
#     '127.0.0.1',
#     'stablelinkcapitalrailway-production.up.railway.app',
#     'stablelinkcapital.com',
#     'www.stablelinkcapital.com',
# ]

# if 'RAILWAY_STATIC_URL' in os.environ:
#     ALLOWED_HOSTS.append(os.environ.get('RAILWAY_PUBLIC_DOMAIN', ''))



# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'home',
#     'userprofile',
#     'django_countries',
#     'connectwallet',
#     'investment',
#     'widget_tweaks',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     "whitenoise.middleware.WhiteNoiseMiddleware",  
# ]

# ROOT_URLCONF = 'stablelinkcapital.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'stablelinkcapital.wsgi.application'


# # import dj_database_url
# # import os

# # DATABASE_URL = os.getenv("DATABASE_URL")

# # if DATABASE_URL:
# #     print("🔵 Using PRODUCTION/PostgreSQL database from DATABASE_URL")
# #     DATABASES = {
# #         'default': dj_database_url.config(conn_max_age=600)
# #     }
# # else:
# #     print("🟢 Using LOCAL SQLite database")
# #     DATABASES = {
# #         'default': {
# #             'ENGINE': 'django.db.backends.sqlite3',
# #             'NAME': BASE_DIR / 'db.sqlite3',
# #         }
# #     }


# import dj_database_url
# import os


# DATABASES = {
#     'default': dj_database_url.config(
#         default=os.environ.get("DATABASE_URL"),
#         conn_max_age=600
#     )
# }



# # Password validation
# # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/


# STATIC_URL = "/static/"

# if DEBUG:
#     # LOCAL DEVELOPMENT (Django serves static files)
#     STATICFILES_DIRS = [
#         BASE_DIR / "static",   # only if you have a local static/ folder
#     ]
# else:
#     # PRODUCTION (WhiteNoise serves static files)
#     STATIC_ROOT = BASE_DIR / "staticfiles"
#     STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# # For production (collectstatic)
# STATIC_ROOT = BASE_DIR / "staticfiles"  

# # For production (collectstatic)
# STATIC_ROOT = BASE_DIR / "staticfiles"  

# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"



# # Default primary key field type
# # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'






# LOGIN_URL = '/userprofile/login/'
# # Force HTTPS in Django
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.zoho.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'support@host.com'
# EMAIL_HOST_PASSWORD = ''   # Zoho APP PASSWORD
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# ADMIN_EMAIL = "support@admin.com"



# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,

#     'formatters': {
#         'verbose': {
#             'format': '[{levelname}] {asctime} {name}:{lineno} - {message}',
#             'style': '{',
#         },
#     },

#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#             'formatter': 'verbose',
#         },
#         'debug_file': {
#             'class': 'logging.FileHandler',
#             'filename': BASE_DIR / 'debug.log',
#             'level': 'DEBUG',
#             'formatter': 'verbose',
#         },
#         'error_file': {
#             'class': 'logging.FileHandler',
#             'filename': BASE_DIR / 'error.log',
#             'level': 'ERROR',
#             'formatter': 'verbose',
#         },
#     },

#     'loggers': {
#         # Catch ALL logs from ALL apps, libraries, and Django itself
#         '': {   # root logger (VERY IMPORTANT)
#             'handlers': ['console', 'debug_file', 'error_file'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },

#         # Django internal logging (500 errors, warnings)
#         'django': {
#             'handlers': ['console', 'error_file'],
#             'level': 'ERROR',
#             'propagate': False,
#         },

#         # Django request/response exceptions
#         'django.request': {
#             'handlers': ['error_file', 'console'],
#             'level': 'ERROR',
#             'propagate': False,
#         },
#     }
# }



# CSRF_TRUSTED_ORIGINS = [
#     "https://stablelinkcapitalrailway-production.up.railway.app",
#     "https://www.stablelinkcapital.com",
#     "https://stablelinkcapital.com",
# ]

"""
Django settings for stablelinkcapital project.
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

load_dotenv()

# Base directory
BASE_DIR = Path(__file__).resolve().parent.parent

# SECRET KEY
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-dev-key"  # fallback for local only
)

# DEBUG
DEBUG = os.getenv("DEBUG", "False") == "True"

# Allowed hosts
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "stablelinkcapitalrailway-production.up.railway.app",
    "stablelinkcapital.com",
    "www.stablelinkcapital.com",
]

# CSRF trusted origins
CSRF_TRUSTED_ORIGINS = [
    "https://stablelinkcapitalrailway-production.up.railway.app",
    "https://stablelinkcapital.com",
    "https://www.stablelinkcapital.com",
]

# Applications
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Your apps
    "home",
    "userprofile",
    "django_countries",
    "connectwallet",
    "investment",
    "widget_tweaks",
]

# Middleware
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",   # MUST be here
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "stablelinkcapital.urls"

# Templates
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "stablelinkcapital.wsgi.application"

# Database (Railway PostgreSQL)
DATABASES = {
    "default": dj_database_url.config(
        default=os.getenv("DATABASE_URL"),
        conn_max_age=600,
    )
}

# Password Validators
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ---------------------------------------
# STATIC FILES — FIXED FOR RAILWAY
# ---------------------------------------

STATIC_URL = "/static/"

# Static root (ALWAYS needed on Railway)
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise handles file compression/caching
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Local static folder
if DEBUG:
    STATICFILES_DIRS = [BASE_DIR / "static"]

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Login redirect
LOGIN_URL = "/userprofile/login/"

# ---------------------------------------
# SECURITY SETTINGS
# ---------------------------------------
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# ---------------------------------------
# EMAIL (placeholder)
# ---------------------------------------
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.zoho.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# ---------------------------------------
# LOGGING
# ---------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "root": {"handlers": ["console"], "level": "INFO"},
}
